name: buy_sell_app
description: Buy Sell Used Products

publish_to: 'none'

version: 1.2.4+24

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  uuid: ^3.0.7
  intl: ^0.17.0
  timeago: ^3.3.0
  location: ^4.4.0
  latlong2: ^0.8.1
  ionicons: ^0.2.2
  provider: ^6.0.5
  geocoding: ^2.0.5
  getwidget: ^3.0.1
  share_plus: ^6.3.0
  cloudinary: ^1.1.0
  flutter_map: ^3.1.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  in_app_review: ^2.0.6
  path_provider: ^2.0.12
  image_picker: ^0.8.6+1
  auto_size_text: ^3.0.0
  google_sign_in: ^5.4.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  dropdown_button2: ^1.9.2
  email_validator: ^2.1.17
  cloudinary_dart: ^0.0.10
  package_info_plus: ^3.0.2
  google_mobile_ads: ^2.3.0
  connectivity_plus: ^3.0.2
  purchases_flutter: ^4.8.0
  cloudinary_flutter: ^0.0.4
  firebase_messaging: ^14.2.1
  permission_handler: ^10.2.0
  flutter_email_sender: ^5.2.0
  firebase_app_check: ^0.1.1+8
  cached_network_image: ^3.2.3
  firebase_ui_firestore: ^1.2.3
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.2.17
  flutter_local_notifications: ^13.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_native_splash:
  branding: assets/play_store_512.png
  color: "#02b866"
  android: true
  ios: true
  android_12:
    branding: assets/play_store_512.png
    color: "#02b866"

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/Rubik-Bold.ttf
          weight: 700
        - asset: assets/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/Rubik-Medium.ttf
          weight: 500
        - asset: assets/Rubik-Regular.ttf
          weight: 400
        - asset: assets/Rubik-Light.ttf
          weight: 300

  assets:
    - assets/no-network.png
    - assets/play_store_512.png
