name: buy_sell_app
description: Buy Sell Used Products Nearby

publish_to: 'none'

version: 1.8.3+57

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  uuid: ^3.0.7
  intl: ^0.17.0
  timeago: ^3.3.0
  location: ^4.4.0
  latlong2: ^0.8.1
  ionicons: ^0.2.2
  provider: ^6.0.5
  geocoding: ^2.1.0
  share_plus: ^7.0.0
  # cloudinary: ^1.1.1
  flutter_map: ^4.0.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  rating_dialog: ^2.0.4
  in_app_review: ^2.0.6
  firebase_auth: ^4.5.0
  path_provider: ^2.0.15
  auto_size_text: ^3.0.0
  firebase_core: ^2.11.0
  google_sign_in: ^6.1.0
  image_picker: ^0.8.7+4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.6.0
  email_validator: ^2.1.17
  # cloudinary_dart: ^0.0.11
  firebase_storage: ^11.1.2
  package_info_plus: ^4.0.0
  google_mobile_ads: ^3.0.0
  connectivity_plus: ^3.0.6
  purchases_flutter: ^4.12.0
  shared_preferences: ^2.1.1
  firebase_app_check: ^0.1.3
  # cloudinary_flutter: ^0.0.5
  firebase_messaging: ^14.5.0
  permission_handler: ^10.2.0
  firebase_performance: ^0.9.2
  flutter_email_sender: ^5.2.0
  cached_network_image: ^3.2.3
  firebase_ui_firestore: ^1.4.0
  flutter_native_image: ^0.0.6+1
  loading_animation_widget: ^1.2.0+4
  flutter_staggered_grid_view: ^0.6.2
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^14.0.0+1
  animated_bottom_navigation_bar: ^1.2.0
  material_design_icons_flutter: ^6.0.7096

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  background_image: "assets/splash_screen.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/no-network.png
    - assets/play_store_512.png
    - assets/madewith.png
    - assets/splash_screen.png
