name: buy_sell_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  uuid: ^3.0.6
  intl: ^0.17.0
  timeago: ^3.3.0
  pinput: ^2.2.16
  confetti: ^0.7.0
  location: ^4.4.0
  provider: ^6.0.3
  geocoding: ^2.0.5
  animations: ^2.0.7
  share_plus: ^6.0.1
  search_page: ^2.2.0
  photo_view: ^0.14.0
  like_button: ^2.0.5
  google_fonts: ^3.0.1
  chat_bubbles: ^1.3.1
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  auto_size_text: ^3.0.0
  google_sign_in: ^5.4.2
  device_preview: ^1.1.0
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  cloud_firestore: ^4.0.4
  dropdown_button2: ^1.8.2
  email_validator: ^2.1.17
  connectivity_plus: ^3.0.2
  flutterfire_ui: ^0.4.3+14
  firebase_storage: ^11.0.4
  flutter_neumorphic: ^3.2.0
  firebase_messaging: ^14.0.4
  top_snackbar_flutter: ^2.1.1
  firebase_app_check: ^0.1.1+3
  cached_network_image: ^3.2.2
  font_awesome_flutter: ^10.2.1
  flutter_native_splash: ^2.2.11
  flutter_staggered_grid_view: ^0.6.2
  flutter_local_notifications: ^12.0.3
  internet_connection_checker: ^1.0.0+1
  animated_bottom_navigation_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#4361ee"

flutter:
  uses-material-design: true
  # assets:
  #   - assets/video.mp4
