name: buy_sell_app
description: Buy Sell Used Products Nearby

publish_to: 'none'

version: 1.5.1+35

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  uuid: ^3.0.7
  intl: ^0.17.0
  timeago: ^3.3.0
  location: ^4.4.0
  latlong2: ^0.8.1
  ionicons: ^0.2.2
  provider: ^6.0.5
  geocoding: ^2.0.5
  getwidget: ^3.0.1
  share_plus: ^6.3.1
  cloudinary: ^1.1.0
  flutter_map: ^3.1.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  in_app_review: ^2.0.6
  path_provider: ^2.0.13
  image_picker: ^0.8.7
  auto_size_text: ^3.0.0
  google_sign_in: ^6.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.4
  email_validator: ^2.1.17
  cloudinary_dart: ^0.0.11
  package_info_plus: ^3.0.3
  google_mobile_ads: ^2.3.0
  connectivity_plus: ^3.0.3
  purchases_flutter: ^4.10.4
  cloudinary_flutter: ^0.0.5
  firebase_messaging: ^14.2.6
  permission_handler: ^10.2.0
  flutter_email_sender: ^5.2.0
  cached_network_image: ^3.2.3
  firebase_app_check: ^0.1.1+13
  firebase_ui_firestore: ^1.2.9
  flutter_native_image: ^0.0.6+1
  flutter_local_notifications: ^13.0.0
  internet_connection_checker: ^1.0.0+1
  animated_bottom_navigation_bar: ^1.2.0
  material_design_icons_flutter: ^6.0.7096

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  background_image: "assets/splash_screen.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/no-network.png
    - assets/play_store_512.png
    - assets/madewith.png
    - assets/splash_screen.png
