name: buy_sell_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.10
  firebase_auth: ^3.9.0
  google_sign_in: ^5.4.2
  cloud_firestore: ^3.4.8
  location: ^4.4.0
  geocode: ^1.0.2
  country_state_city_pro: ^0.0.3
  csc_picker: ^0.2.6
  email_validator: ^2.1.17
  auto_size_text: ^3.0.0
  dropdown_button2: ^1.8.2
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  provider: ^6.0.3
  uuid: 3.0.6
  page_transition: ^2.0.9
  confetti: ^0.7.0
  timeago: ^3.3.0
  like_button: ^2.0.5
  dot_navigation_bar: ^1.0.1+4
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.2.11
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#4361ee"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
